# name: Deploy to Hostinger

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Project
#         run: npm run build

#       - name: Deploy via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           protocol: ftp
#           server-dir: /public_html/
#           local-dir: build/
#           exclude: |
#             **/.htaccess
#             **/.env


name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---- 1️⃣ Pull the code -------------------------------------------------
      - name: Checkout Repo
        uses: actions/checkout@v3

      # ---- 2️⃣ Install a known Node version ----------------------------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'          # pick whatever your project needs
          cache: 'npm'

      # ---- 3️⃣ Install deps -------------------------------------------------
      - name: Install Dependencies
        run: npm ci                     # clean install, reproducible

      # ---- 4️⃣ Build ---------------------------------------------------------
      - name: Build Project
        run: npm run build

      # ---- 5️⃣ Deploy via FTP ------------------------------------------------
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          # Hostinger usually needs explicit TLS (FTPS). Switch to `ftps` if
          # you’ve enabled “SSL/TLS” in their control panel.
          protocol: ftp                # or keep `ftp` if you know plain works
          port: 21                     # default, but explicit never hurts

          # Keep the path relative to the FTP user’s home. Most hosted accounts
          # already land you in `/public_html`, so omit the leading slash.
          server-dir: public_html

          # Adjust to whatever your build script spits out.
          local-dir: build

          # Exclude files you truly don’t want to upload.
          exclude: |
            **/.htaccess
            **/.env

          # Force passive mode (works for almost every shared host)
          passive: true